"""Initial schema

Revision ID: 84671c008e59
Revises: 
Create Date: 2026-03-08 20:06:13.894560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84671c008e59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('src_ip', sa.String(), nullable=True),
    sa.Column('dst_ip', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_log_dst_ip'), 'threat_log', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_threat_log_src_ip'), 'threat_log', ['src_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_log_src_ip'), table_name='threat_log')
    op.drop_index(op.f('ix_threat_log_dst_ip'), table_name='threat_log')
    op.drop_table('threat_log')
    # ### end Alembic commands ###
